stages:
  - build
  - clean

.build:vagrant:ubunt-18.04-lts:
  stage: build
  script:
    - packer version
    - pushd vb-ubuntu-18.04-lts
    - VBOX_VERSION=$(VBoxHeadless --version | head -n 1 | awk '{print $NF}' | cut -f1 -d'_')
    - echo $VBOX_VERSION
    - packer build -parallel-builds=1 --var disk_size=102400 --var virtualbox_version=$VBOX_VERSION --var headless=true box.json
  tags:
    - packer
  only:
    changes:
      - "vb-ubuntu-18.04-lts/*"
  except:
    - triggers

.build:vagrant:nominatim:
  stage: build
  when: manual
  #resource_group: packer
  variables:
    PACKER_LOG: 0
    REGION: "TO_OVERWRITE_IN_CHILD_JOB"
    REGION_DATA_URL: "TO_OVERWRITE_IN_CHILD_JOB"
  script:
    - packer version
    - pushd vagrant-nominatim
    - echo "REGION ${REGION}"
    - echo "REGION_DATA_URL ${REGION_DATA_URL}"
    - packer build -var "region=${REGION}" -var "region_data_url=${REGION_DATA_URL}" -var "skip_add=true" box.json
  tags:
    - packer

build:vagrant:nominatim-monaco:
  extends: .build:vagrant:nominatim
  variables:
    REGION: monaco
    REGION_DATA_URL: https://download.geofabrik.de/europe/monaco-latest.osm.pbf

build:vagrant:nominatim-poland:
  extends: .build:vagrant:nominatim
  variables:
    REGION: poland
    REGION_DATA_URL: https://download.geofabrik.de/europe/poland-latest.osm.pbf

build:vagrant:nominatim-britain-and-ireland:
  extends: .build:vagrant:nominatim
  variables:
    REGION: britain-and-ireland
    REGION_DATA_URL: https://download.geofabrik.de/europe/britain-and-ireland-latest.osm.pbf

build:docker:node10-google-chrome:
  stage: build
  script:
    - packer version
    - pushd node10-google-chrome
    - DOCKER_TOKEN=$DOCKER_HUB_TOKEN packer build box.json
    - GOOGLE_CHROME_VERSION=$(docker run --rm morawskim/node10-google-chrome google-chrome --version)
    - echo 'google chrome version - ' $GOOGLE_CHROME_VERSION
    - TAG=$(echo $GOOGLE_CHROME_VERSION | awk '{print $NF}' | cut -d'.' -f 1-2)
    - echo 'TAG - ' $TAG
    - DOCKER_TOKEN=$DOCKER_HUB_TOKEN packer build --var docker_tag=$TAG box-tag.json
    - docker image rm morawskim/node10-google-chrome morawskim/node10-google-chrome:$TAG
  tags:
    - packer
  only:
    changes:
      - "node10-google-chrome/*"
  except:
    - triggers

build:docker:node12-google-chrome:
  stage: build
  script:
    - packer version
    - pushd node12-google-chrome
    - DOCKER_TOKEN=$DOCKER_HUB_TOKEN packer build box.json
    - GOOGLE_CHROME_VERSION=$(docker run --rm morawskim/node12-google-chrome google-chrome --version)
    - echo 'google chrome version - ' $GOOGLE_CHROME_VERSION
    - TAG=$(echo $GOOGLE_CHROME_VERSION | awk '{print $NF}' | cut -d'.' -f 1-2)
    - echo 'TAG - ' $TAG
    - DOCKER_TOKEN=$DOCKER_HUB_TOKEN packer build --var docker_tag=$TAG box-tag.json
    - docker image rm morawskim/node12-google-chrome morawskim/node12-google-chrome:$TAG
  tags:
    - packer
  only:
    changes:
      - "node12-google-chrome/*"
  except:
    - triggers

build:docker:collectd-web:
  stage: build
  script:
    - packer version
    - pushd collectd-web
    - DOCKER_TOKEN=$DOCKER_HUB_TOKEN packer build box.json
  tags:
    - packer
  only:
    changes:
      - "collectd-web/*"
  except:
    - triggers

build:docker:htrace.sh:
  stage: build
  script:
    - cd htrace.sh
    - VERSION=$(curl -sL https://api.github.com/repos/trimstray/htrace.sh/git/matching-refs/tags | jq '.[].ref' | cut -c13- | rev | cut -c2- | rev | sed -n '/^[[:digit:]]\.[[:digit:]]\.[[:digit:]]$/p' | sort -r --version-sort | head -1)
    - git clone --branch v$VERSION -- https://github.com/trimstray/htrace.sh.git
    - cd htrace.sh
    - docker build --no-cache -t $NAME -f build/Dockerfile .
    - cd ..
    - rm -rf ./htrace.sh
    - DOCKER_TOKEN=$DOCKER_HUB_TOKEN packer build --var docker_tag=$VERSION box.json
  variables:
    NAME: htrace.sh
  tags:
    - packer
  only:
    changes:
      - "htrace.sh/*"
  except:
    - triggers

build:docker:webgrind:
  stage: build
  script:
    - packer version
    - pushd webgrind
    - VERSION=$(curl -sL https://api.github.com/repos/jokkedk/webgrind/releases/latest | jq -r '.tarball_url')
    - TAG=$(basename $VERSION | cut -c2-)
    - echo 'TAG - ' $TAG
    - DOCKER_TOKEN=$DOCKER_HUB_TOKEN packer build --var docker_tag=$TAG box.json
  tags:
    - packer
  only:
    changes:
      - "webgrind/*"
  except:
    - triggers

build:docker:swaks:
  stage: build
  when: manual
  allow_failure: false
  script:
    - packer version
    - pushd swaks
    - TAG=20190914.0
    - echo 'TAG - ' $TAG
    - DOCKER_TOKEN=$DOCKER_HUB_TOKEN packer build --var docker_tag=$TAG box.json
  tags:
    - packer
  only:
    changes:
      - "swaks/*"
  except:
    - triggers

build:docker:csvsql-mysql:
  stage: build
  script:
    - packer version
    - pushd csvsql-mysql
    - VERSION=$(curl -sL https://api.github.com/repos/wireservice/csvkit/git/matching-refs/tags | jq '.[].ref' | cut -c12- | rev | cut -c2- | rev | sed -n '/^[[:digit:]]\.[[:digit:]]\.[[:digit:]]$/p' | sort -r --version-sort | head -1)
    - echo 'TAG - ' $VERSION
    - >
      if curl --silent -f --head -lL https://hub.docker.com/v2/repositories/morawskim/csvsql-mysql/tags/$VERSION/ > /dev/null; then
        echo "Image already exists, so skip build and push"
      else
        DOCKER_TOKEN=$DOCKER_HUB_TOKEN packer build --var docker_tag=$VERSION box.json
      fi
  tags:
    - packer
  only:
    changes:
      - "csvsql-mysql/*"
  except:
    - triggers

build:docker:php53v:
  stage: build
  script:
    - packer version
    - pushd php53v
    - DOCKER_TOKEN=$DOCKER_HUB_TOKEN packer build box.json
  tags:
    - packer
  only:
    changes:
      - "php53v/*"
  except:
    - triggers

build:docker:php54v:
  stage: build
  script:
    - packer version
    - pushd php54v
    - DOCKER_TOKEN=$DOCKER_HUB_TOKEN packer build box.json
  tags:
    - packer
  only:
    changes:
      - "php54v/*"
  except:
    - triggers

build:docker:php55v:
  stage: build
  script:
    - packer version
    - pushd php55v
    - DOCKER_TOKEN=$DOCKER_HUB_TOKEN packer build box.json
  tags:
    - packer
  only:
    changes:
      - "php55v/*"
  except:
    - triggers

build:docker:php56v:
  stage: build
  script:
    - packer version
    - pushd php56v
    - DOCKER_TOKEN=$DOCKER_HUB_TOKEN packer build box.json
  tags:
    - packer
  only:
    changes:
      - "php56v/*"
  except:
    - triggers

build:docker:opensuse-15.0-debug:
  stage: build
  script:
    - packer version
    - pushd opensuse-15.0-debug
    - DOCKER_TOKEN=$DOCKER_HUB_TOKEN packer build box.json
  tags:
    - packer
  only:
    changes:
      - "opensuse-15.0-debug/*"
  except:
    - triggers

build:docker:opensuse-15.0-kde:
  stage: build
  script:
    - packer version
    - pushd opensuse-15.0-kde
    - DOCKER_TOKEN=$DOCKER_HUB_TOKEN packer build box.json
    - >
      curl --fail -X POST --form token=${TRIGGER_TOKEN} --form ref=$CI_COMMIT_REF_NAME --form "variables[BUILD_KDE_DEV]=1" https://gitlab.com/api/v4/projects/$CI_PROJECT_ID/trigger/pipeline
  tags:
    - packer
  only:
    changes:
      - "opensuse-15.0-kde/*"
  except:
    - triggers

build:docker:opensuse-15.0-kde-devel:
  stage: build
  script:
    - packer version
    - pushd opensuse-15.0-kde-devel
    - DOCKER_TOKEN=$DOCKER_HUB_TOKEN packer build box.json
  tags:
    - packer
  only:
    refs:
      - triggers
    variables:
      - $BUILD_KDE_DEV == "1"

clean:
  stage: clean
  when: always
  script:
    - docker image prune --force
  tags:
    - packer
