stages:
  - build

build:docker:node10-google-chrome:
  stage: build
  when: manual
  allow_failure: false
  script:
    - packer version
    - pushd node10-google-chrome
    - DOCKER_TOKEN=$DOCKER_HUB_TOKEN packer build box.json
    - GOOGLE_CHROME_VERSION=$(docker run --rm morawskim/node10-google-chrome 'google-chrome --version')
    - echo 'google chrome version - ' $GOOGLE_CHROME_VERSION
    - TAG=$(echo $GOOGLE_CHROME_VERSION | awk '{print $NF}' | cut -d'.' -f 1-2)
    - echo 'TAG - ' $TAG
    - DOCKER_TOKEN=$DOCKER_HUB_TOKEN packer build --var docker_tag=$TAG box-tag.json
  tags:
    - packer
