stages:
  - build

build:vagrant:ubunt-18.04-lts:
  stage: build
  when: manual
  allow_failure: false
  script:
    - packer version
    - pushd vb-ubuntu-18.04-lts
    - VBOX_VERSION=$(VBoxHeadless --version | head -n 1 | awk '{print $NF}' | cut -f1 -d'_')
    - echo $VBOX_VERSION
    - packer build --var disk_size=102400 --var virtualbox_version=$VBOX_VERSION --var headless=true box.json
    #TODO: copy to nexus
    - cp Ubuntu-18.04-amd64-minimal-v1.0.0-virtualbox.box /tmp
  tags:
    - packer

build:docker:node10-google-chrome:
  stage: build
  when: manual
  allow_failure: false
  script:
    - packer version
    - pushd node10-google-chrome
    - DOCKER_TOKEN=$DOCKER_HUB_TOKEN packer build box.json
    - GOOGLE_CHROME_VERSION=$(docker run --rm morawskim/node10-google-chrome google-chrome --version)
    - echo 'google chrome version - ' $GOOGLE_CHROME_VERSION
    - TAG=$(echo $GOOGLE_CHROME_VERSION | awk '{print $NF}' | cut -d'.' -f 1-2)
    - echo 'TAG - ' $TAG
    - DOCKER_TOKEN=$DOCKER_HUB_TOKEN packer build --var docker_tag=$TAG box-tag.json
  tags:
    - packer

build:docker:collectd-web:
  stage: build
  when: manual
  allow_failure: false
  script:
    - packer version
    - pushd collectd-web
    - DOCKER_TOKEN=$DOCKER_HUB_TOKEN packer build box.json
  tags:
    - packer

build:docker:htrace.sh:
  stage: build
  when: manual
  allow_failure: false
  script:
    - cd htrace.sh
    - git clone --branch v$VERSION -- https://github.com/trimstray/htrace.sh.git
    - cd htrace.sh
    - docker build --no-cache -t $NAME -f build/Dockerfile .
    - cd ..
    - rm -rf ./htrace.sh
    - DOCKER_TOKEN=$DOCKER_HUB_TOKEN packer build --var docker_tag=$VERSION box.json
  variables:
    VERSION: 1.1.6
    NAME: htrace.sh
  tags:
    - packer

build:docker:php53v:
  stage: build
  when: manual
  allow_failure: false
  script:
    - packer version
    - pushd php53v
    - DOCKER_TOKEN=$DOCKER_HUB_TOKEN packer build box.json
  tags:
    - packer

build:docker:php54v:
  stage: build
  when: manual
  allow_failure: false
  script:
    - packer version
    - pushd php54v
    - DOCKER_TOKEN=$DOCKER_HUB_TOKEN packer build box.json
  tags:
    - packer

build:docker:php55v:
  stage: build
  when: manual
  allow_failure: false
  script:
    - packer version
    - pushd php55v
    - DOCKER_TOKEN=$DOCKER_HUB_TOKEN packer build box.json
  tags:
    - packer

build:docker:php56v:
  stage: build
  when: manual
  allow_failure: false
  script:
    - packer version
    - pushd php56v
    - DOCKER_TOKEN=$DOCKER_HUB_TOKEN packer build box.json
  tags:
    - packer

build:docker:opensuse-15.0-debug:
  stage: build
  when: manual
  allow_failure: false
  script:
    - packer version
    - pushd opensuse-15.0-debug
    - DOCKER_TOKEN=$DOCKER_HUB_TOKEN packer build box.json
  tags:
    - packer

build:docker:opensuse-15.0-kde:
  stage: build
  when: manual
  allow_failure: false
  script:
    - packer version
    - pushd opensuse-15.0-kde
    - DOCKER_TOKEN=$DOCKER_HUB_TOKEN packer build box.json
  tags:
    - packer

