stages:
  - build

.build:vagrant:ubunt-18.04-lts:
  stage: build
  script:
    - packer version
    - pushd vb-ubuntu-18.04-lts
    - VBOX_VERSION=$(VBoxHeadless --version | head -n 1 | awk '{print $NF}' | cut -f1 -d'_')
    - echo $VBOX_VERSION
    - packer build --var disk_size=102400 --var virtualbox_version=$VBOX_VERSION --var headless=true box.json
    #TODO: copy to nexus
    - cp Ubuntu-18.04-amd64-minimal-v1.0.0-virtualbox.box /tmp
  tags:
    - packer
  only:
    changes:
      - "vb-ubuntu-18.04-lts/*"
  except:
    - triggers

build:docker:node10-google-chrome:
  stage: build
  script:
    - packer version
    - pushd node10-google-chrome
    - DOCKER_TOKEN=$DOCKER_HUB_TOKEN packer build box.json
    - GOOGLE_CHROME_VERSION=$(docker run --rm morawskim/node10-google-chrome google-chrome --version)
    - echo 'google chrome version - ' $GOOGLE_CHROME_VERSION
    - TAG=$(echo $GOOGLE_CHROME_VERSION | awk '{print $NF}' | cut -d'.' -f 1-2)
    - echo 'TAG - ' $TAG
    - DOCKER_TOKEN=$DOCKER_HUB_TOKEN packer build --var docker_tag=$TAG box-tag.json
    - docker image rm morawskim/node10-google-chrome morawskim/node10-google-chrome:$TAG
  tags:
    - packer
  only:
    changes:
      - "node10-google-chrome/*"
  except:
    - triggers

build:docker:collectd-web:
  stage: build
  script:
    - packer version
    - pushd collectd-web
    - DOCKER_TOKEN=$DOCKER_HUB_TOKEN packer build box.json
  tags:
    - packer
  only:
    changes:
      - "collectd-web/*"
  except:
    - triggers

build:docker:htrace.sh:
  stage: build
  script:
    - cd htrace.sh
    - git clone --branch v$VERSION -- https://github.com/trimstray/htrace.sh.git
    - cd htrace.sh
    - docker build --no-cache -t $NAME -f build/Dockerfile .
    - cd ..
    - rm -rf ./htrace.sh
    - DOCKER_TOKEN=$DOCKER_HUB_TOKEN packer build --var docker_tag=$VERSION box.json
  variables:
    VERSION: 1.1.6
    NAME: htrace.sh
  tags:
    - packer
  only:
    changes:
      - "htrace.sh/*"
  except:
    - triggers

build:docker:webgrind:
  stage: build
  script:
    - packer version
    - pushd webgrind
    - VERSION=$(curl -sL https://api.github.com/repos/jokkedk/webgrind/releases/latest | jq -r '.tarball_url')
    - TAG=$(basename $VERSION | cut -c2-)
    - echo 'TAG - ' $TAG
    - DOCKER_TOKEN=$DOCKER_HUB_TOKEN packer build --var docker_tag=$TAG box.json
  tags:
    - packer
  only:
    changes:
      - "webgrind/*"
  except:
    - triggers

build:docker:php53v:
  stage: build
  script:
    - packer version
    - pushd php53v
    - DOCKER_TOKEN=$DOCKER_HUB_TOKEN packer build box.json
  tags:
    - packer
  only:
    changes:
      - "php53v/*"
  except:
    - triggers

build:docker:php54v:
  stage: build
  script:
    - packer version
    - pushd php54v
    - DOCKER_TOKEN=$DOCKER_HUB_TOKEN packer build box.json
  tags:
    - packer
  only:
    changes:
      - "php54v/*"
  except:
    - triggers

build:docker:php55v:
  stage: build
  script:
    - packer version
    - pushd php55v
    - DOCKER_TOKEN=$DOCKER_HUB_TOKEN packer build box.json
  tags:
    - packer
  only:
    changes:
      - "php55v/*"
  except:
    - triggers

build:docker:php56v:
  stage: build
  script:
    - packer version
    - pushd php56v
    - DOCKER_TOKEN=$DOCKER_HUB_TOKEN packer build box.json
  tags:
    - packer
  only:
    changes:
      - "php56v/*"
  except:
    - triggers

build:docker:opensuse-15.0-debug:
  stage: build
  script:
    - packer version
    - pushd opensuse-15.0-debug
    - DOCKER_TOKEN=$DOCKER_HUB_TOKEN packer build box.json
  tags:
    - packer
  only:
    changes:
      - "opensuse-15.0-debug/*"
  except:
    - triggers

build:docker:opensuse-15.0-kde:
  stage: build
  script:
    - packer version
    - pushd opensuse-15.0-kde
    - DOCKER_TOKEN=$DOCKER_HUB_TOKEN packer build box.json
    - >
      curl --fail -X POST --form token=${TRIGGER_TOKEN} --form ref=$CI_COMMIT_REF_NAME --form "variables[BUILD_KDE_DEV]=1" https://gitlab.sensilabs.pl/api/v4/projects/$CI_PROJECT_ID/trigger/pipeline
  tags:
    - packer
  only:
    changes:
      - "opensuse-15.0-kde/*"
  except:
    - triggers

build:docker:opensuse-15.0-kde-devel:
  stage: build
  script:
    - packer version
    - pushd opensuse-15.0-kde-devel
    - DOCKER_TOKEN=$DOCKER_HUB_TOKEN packer build box.json
    - docker image rm morawskim/opensuse-15.0-kde
  tags:
    - packer
  only:
    refs:
      - triggers
    variables:
      - $BUILD_KDE_DEV == "1"
